interface Feedback {
  id: string;
  interviewId: string;
  totalScore: number;
  categoryScores: Array<{
    name: string;
    score: number;
    comment: string;
  }>;
  strengths: string[];
  areasForImprovement: string[];
  finalAssessment: string;
  createdAt: string;
}

interface Interview {
  id: string;
  role: string;
  level: string;
  questions: string[];
  techstack: string[];
  createdAt: string;
  userId: string;
  type: string;
  finalized: boolean;
}

interface CreateFeedbackParams {
  interviewId: string;
  userId: string;
  transcript: { role: string; content: string }[];
  feedbackId?: string;
}

interface User {
  name: string;
  email: string;
  id: string;
}

interface InterviewCardProps {
  id?: string;
  userId?: string;
  role: string;
  type: string;
  techstack: string[];
  createdAt?: string;
}

interface AgentProps {
  userName: string;
  userId?: string;
  interviewId?: string;
  feedbackId?: string;
  type: "generate" | "interview";
  questions?: string[];
}

interface RouteParams {
  params: Promise<Record<string, string>>;
  searchParams: Promise<Record<string, string>>;
}

interface GetFeedbackByInterviewIdParams {
  interviewId: string;
  userId: string;
}

interface GetLatestInterviewsParams {
  userId: string;
  limit?: number;
}

interface SignInParams {
  email: string;
  idToken: string;
}

interface SignUpParams {
  uid: string;
  name: string;
  email: string;
  password: string;
}

type FormType = "sign-in" | "sign-up";

interface InterviewFormProps {
  interviewId: string;
  role: string;
  level: string;
  type: string;
  techstack: string[];
  amount: number;
}

interface TechIconProps {
  techStack: string[];
}

// Aptitude Assessment Types
interface AssessmentQuestionChoice {
  id: string; // e.g., "A", "B", "C", "D"
  text: string;
}

interface AssessmentQuestion {
  id: string;
  topic: string; // e.g., "Aptitude", "DSA", "OS"
  difficulty: "easy" | "medium" | "hard";
  question: string;
  choices: AssessmentQuestionChoice[];
  correctChoiceId: string; // server only; do not send to client when active
  explanation?: string; // short explanation for result page
}

interface AssessmentSession {
  id: string;
  userId: string;
  topics: string[];
  numQuestions: number;
  durationMinutes: number;
  difficulty: "easy" | "medium" | "hard" | "mixed";
  createdAt: string;
  status: "pending" | "active" | "submitted" | "autofailed";
}

interface CreateAssessmentParams {
  userId: string;
  topics: string[];
  numQuestions: number;
  durationMinutes: number;
  difficulty: "easy" | "medium" | "hard" | "mixed";
}

interface SubmitAssessmentParams {
  sessionId: string;
  userId: string;
  answers: Array<{ questionId: string; choiceId: string | null }>;
  reason?: "user_submit" | "timeout" | "proctor_violation";
}

interface AssessmentResultSummary {
  sessionId: string;
  userId: string;
  totalQuestions: number;
  correct: number;
  incorrect: number;
  unanswered: number;
  scorePercent: number; // 0..100
  topicBreakdown: Array<{ topic: string; correct: number; total: number }>;
  difficultyBreakdown: Array<{
    difficulty: "easy" | "medium" | "hard";
    correct: number;
    total: number;
  }>;
  createdAt: string;
  aiSuggestions?: string; // markdown/text suggestions generated by AI
}

// Coding Assessment Types
interface CodingProblemExample {
  input: string;
  output: string;
  explanation?: string;
}

interface CodingProblem {
  id: string;
  topic: string; // e.g., Arrays, Strings, Trees, Stack, Queue
  difficulty: "easy" | "medium" | "hard";
  title: string;
  description: string;
  functionSignature: string; // Java or C++
  inputFormat?: string;
  outputFormat?: string;
  constraints?: string;
  examples: CodingProblemExample[];
  // server-only field (not sent to client when active)
  testCases?: Array<{ input: string; output: string }>;
}

interface CodingSession {
  id: string;
  userId: string;
  topics: string[];
  numQuestions: number;
  durationMinutes: number;
  difficulty: "easy" | "medium" | "hard" | "mixed";
  createdAt: string;
  status: "pending" | "active" | "submitted" | "autofailed";
}

interface CreateCodingParams {
  userId: string;
  topics: string[];
  numQuestions: number;
  durationMinutes: number;
  difficulty: "easy" | "medium" | "hard" | "mixed";
}

interface SubmitCodingParams {
  sessionId: string;
  userId: string;
  language: "java" | "cpp";
  answers: Array<{ problemId: string; code: string }>;
  reason?: "user_submit" | "timeout" | "proctor_violation";
}

interface CodingProblemEvaluation {
  problemId: string;
  passed: number; // number of testcases passed
  total: number; // total testcases
  feedback?: string;
}

interface CodingResultSummary {
  sessionId: string;
  userId: string;
  totalProblems: number;
  totalPassed: number;
  totalTestCases: number;
  scorePercent: number;
  topicBreakdown: Array<{ topic: string; passed: number; total: number }>;
  difficultyBreakdown: Array<{
    difficulty: "easy" | "medium" | "hard";
    passed: number;
    total: number;
  }>;
  createdAt: string;
  aiSuggestions?: string;
  evaluations: CodingProblemEvaluation[];
}
